# Generated by Django 4.0.6 on 2022-07-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_onprocess_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='todo',
            field=models.BooleanField(default=False),
        ),
    ]
