# Generated by Django 4.0.6 on 2022-07-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_task_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('completed', 'COMPLETED'), ('onprocess', 'ONPROCESS'), ('todo', 'TODO')], default='todo', max_length=9),
        ),
    ]
