# Generated by Django 4.0.6 on 2022-07-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='onprocess',
        ),
        migrations.RemoveField(
            model_name='task',
            name='todo',
        ),
    ]
